services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: komik-ci4  # Set the container name here
    ports:
      - "8080:80"  # Map port 80 of the container to port 8080 on the host
    volumes:
      - .:/var/www/html  # Mount current directory to /var/www/html inside the container
    environment:
      - CI_ENVIRONMENT=development